# This is the minimal configuration to start a OpenTelemetry collector
# that collects traces via the otlp protocol, and then sends them via
# batches to a central jaeger collector
#

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: ":8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
