[advisories]
ignore = [
  "RUSTSEC-2020-0071", # `time` localtime_r segfault -- https://rustsec.org/advisories/RUSTSEC-2020-0071
  # Ignored because there are not known workarounds or dependency version bump
  # at this time. The call to localtime_r is not protected by any lock and can
  # cause unsoundness. Read the previous link for more information.
  "RUSTSEC-2020-0168", # This is about "mach" being unmaintained.
  # This is a transitive dependency of wasmtime. This is
  # being tracked upstream via https://github.com/bytecodealliance/wasmtime/issues/6000
  # This is a transitive depependency of sigstore
  "RUSTSEC-2023-0071", # "Classic" RSA timing sidechannel attack from non-constant-time implementation.
  # Okay for local use.
  # https://rustsec.org/advisories/RUSTSEC-2023-0071.html
  "RUSTSEC-2023-0081", # This is about `safemem` being unmaintained.
  # This is a transitive dependency of syntect. This bug is tracked upstream inside of
  # https://github.com/trishume/syntect/issues/521
  "RUSTSEC-2024-0370", # This is a warning about `proc-macro-errors` being unmaintained. It's a transitive dependency of `sigstore` and `oci-spec`.
  "RUSTSEC-2023-0055", # This is a warning about `lexical` having multiple soundness issues. It's a transitive dependency of `sigstore`.
]
