---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1-admissionpolicy
  failurePolicy: Fail
  name: madmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - admissionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1-admissionpolicygroup
  failurePolicy: Fail
  name: madmissionpolicygroup.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - admissionpolicygroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1-clusteradmissionpolicy
  failurePolicy: Fail
  name: mclusteradmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1-clusteradmissionpolicygroup
  failurePolicy: Fail
  name: mclusteradmissionpolicygroup.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicygroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policies-kubewarden-io-v1-policyserver
  failurePolicy: Fail
  name: mpolicyserver.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policyservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1-admissionpolicy
  failurePolicy: Fail
  name: vadmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - admissionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1-admissionpolicygroup
  failurePolicy: Fail
  name: vadmissionpolicygroup.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - admissionpolicygroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1-clusteradmissionpolicy
  failurePolicy: Fail
  name: vclusteradmissionpolicy.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1-clusteradmissionpolicygroup
  failurePolicy: Fail
  name: vclusteradmissionpolicygroup.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradmissionpolicygroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policies-kubewarden-io-v1-policyserver
  failurePolicy: Fail
  name: vpolicyserver.kb.io
  rules:
  - apiGroups:
    - policies.kubewarden.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policyservers
  sideEffects: None
